import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import SplashScreen from "@/components/splash-screen";
import Navbar from "@/components/nav";

const RubikFont = Rubik({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RubikFont.className} antialiased min-h-screen flex flex-col`}
      >
        <SplashScreen>
          <Navbar />
          <main className="flex-1">{children}</main>
        </SplashScreen>
      </body>
    </html>
  );
}
